### ISSUE TITLE
[Error] PLS-00201 (2398: 9): PLS-00201: identifier 'T_X2' must be declared

### ISSUE THREAD

**Issue by nolemlin** [antonscheffer/as_barcode#1]
hi, thank for share , but body compile error with below,can you help ?
    and can you please create qrcode sample plsql for us?

[Error] PLS-00201 (2398: 9): PLS-00201: identifier 'T_X2' must be declared
[Error] PLS-00201 (2403: 11): PLS-00201: identifier 'T_W2' must be declared
[Error] PLS-00201 (2405: 11): PLS-00201: identifier 'T_X1' must be declared
[Error] PLS-00201 (2406: 11): PLS-00201: identifier 'T_X2' must be declared
[Error] PLS-00201 (2407: 62): PLS-00201: identifier 'T_W2' must be declared
[Error] PLS-00201 (2412: 22): PLS-00201: identifier 'T_X1' must be declared
[Error] PLS-00201 (2413: 22): PLS-00201: identifier 'T_X2' must be declared
[Error] PLS-00201 (2414: 25): PLS-00201: identifier 'T_X1' must be declared
[Error] PLS-00201 (2415: 25): PLS-00201: identifier 'T_X2' must be declared
[Error] PLS-00201 (2416: 22): PLS-00201: identifier 'T_X1' must be declared

br,nolem

**Comment by antonscheffer** [comment]
Pushed a new version which fixes this issue.
