### ISSUE TITLE
Request: 4-state barcode

### ISSUE THREAD

**Issue by greenepunty** [antonscheffer/as_barcode#10]
Not sure whether this is the right place to request new functionality, but would you be able to add support for the 4-state barcode format?

**Comment by antonscheffer** [comment]
Never heard of that code. I seems like there are a lot of different varians used in different countries. Which one do you need? And do you have a spec for that?

**Comment by greenepunty** [comment]
Ideally would like the format for Australia Post. Please refer to the following links for specifications:

https://auspost.com.au/content/dam/auspost_corp/media/documents/customer-barcode-technical-specifications-aug2012.pdf
https://auspost.com.au/content/dam/auspost_corp/media/documents/a-guide-to-printing-the-4state-barcode-v31-mar2012.pdf

**Comment by antonscheffer** [comment]
At https://apex.oracle.com/pls/apex/r/excel2collection/demo-for-as-barcode/diy you try out the first version.
Use as parameter {"raise":true, "apsc":true}

**Comment by greenepunty** [comment]
That is fantastic! Awesome work!

**Comment by antonscheffer** [comment]
Pushed the changes
