### ISSUE TITLE
hi, this package can not create multibyte barcode 

### ISSUE THREAD

**Issue by nolemlin** [antonscheffer/as_barcode#2]
hi, i test your package after you update version , if we use single byte , qrcode is fine,
     but i found if i use text with multi-byte language to create qrcode image ,ex:chinese 
     it will lost , and qrcode reader can not parse it .

**Comment by danny-d1** [comment]
Hi nolemlin, did you test crearing QR code the text with multiple lines? it seems the package doesn't break the text into new lines in the QR code image.

**Comment by nolemlin** [comment]
hi,danny-d1, just 1 line with Chinese font and single byte ex:'我是ORCODE喔！'

**Comment by pkateel** [comment]
Is there any possibilities to use this code in Oracle Report Builder? If yes, how to use it?

**Comment by antonscheffer** [comment]
Should be fixed
