### ISSUE TITLE
the package doesn't break text with carriage return into new lines for QR code

### ISSUE THREAD

**Issue by danny-d1** [antonscheffer/as_barcode#4]
Hi, 
I feed into the function AS_BARCODE.barcode('a\n\'||CHR(13)||CHR(10)||'\Nb','QR')
the QR code generated seems doesn't include the line breaks. it show as a\n\ \Nb. 
is this an issue?

**Comment by antonscheffer** [comment]
This is not an issue with as_barcode, it might be an issue with your scanner.
